### PR TITLE
Configure status layer colors

### PR DESCRIPTION
**Pull request by llamahunter**
Allow the status layer's foreground and background colors to be configured.

### CODE REVIEW

**Comment by llamahunter** [comment]
Not clear why the build failed for 3.7, but passed for 2.9 and 3.8.

**Comment by Meiguro** [comment]
Hmm, yes, that failure is strange. I have actually implemented as part of my WIP branch to add Chalk support. You can see a similar commit here: https://github.com/pebble/pebblejs/commit/8fac33b538e8df29e6c5650bb4f0b3f1bd2a1c6f

Our implementations are similar, except I have created a separate packet to encourage changing the color on the fly, requiring less bytes. On the flip side, there are larger costs when switching between windows, which is actually the more common use case. A window with no status bar and no action bar however would also use less bytes. In any case I'm willing to pay the costs for maintainability since each bar is handled separately.

It will still take me a bit to merge https://github.com/pebble/pebblejs/tree/feature-chalk-wip into master (maybe this weekend!) so let me know what you think should happen with this PR.

**Comment by llamahunter** [comment]
Hmm.. I could see the utility of being able to change the status bar colors on the fly for notification purposes.   However, I worry about 'flashing' if the default status bar colors were to display briefly before I was able to use the separate api to change them after the screen transition. My use case is actually a desire to change the status bar color everywhere in the app for 'branding' purposes.  My solution still requires setting the status bar color with every screen transition. Maybe a separate 'global props' packet that sets the status bar (and maybe even the menu color themes) globally for the app would be better?

**Comment by Meiguro** [comment]
Ah, I wrote the underlying packet protocol to take care of this -- packets generated in the same JavaScript process tick are sent as a single group and are not processed until they are received in entirety, and usually it only takes up a single Bluetooth packet. That's actually what the 0th command number represents, a multi-packet packet. With this set up, multiple changes that need to occur synchronously on the watch can be written as separate packets, allowing you leverage the synchronous behavior along with being able to mix which packets you would like.

It's why the Menu in the demo app doesn't flash when it loads even though each item, the menu, and the window properties are all separate.

**Comment by llamahunter** [comment]
Hmm.. so, maybe your solution would be fine?  Still, I imagine it would be kind of nice for other developers to set menu and status colors once on startup for 'branding' rather than for every screen.  Should I create a pull request for that?

**Comment by Meiguro** [comment]
I can explain the underlying protocol more clearly if you like. It would be very concerning if such a pattern didn't work since it would degrade much of the functionality of Pebble.js, especially menus.

Hmm, you have an interesting idea of setting colors once, but I think something like that is for the user to handle. Having a global default for status bar may beg other values to have global defaults, such as text color.  A construct like that would also give preference to having a single style. Some apps can have two or more themes. Pebble firmware 3.0's settings is an example of an app with a dark and light theme.

In the mean time, you can create a function that creates or supplements the values that are passed to the window constructors, or create a function that styles a window accordingly after construction before it is shown.

```javascript
// myStyler takes an initializer
var card = new UI.Card(myStyler({ ... }));

// or myStyler takes properties (same format as initializer)
var card = new UI.Card({ ... });
card.prop(myStyler({ ... }));

// or myStyler operates on the card
var card = new UI.Card({ ... });
myStyler(card);
card.show();
```

You could even wrap new UI.Card completely.

With that said, I don't think styles are a bad idea outright. I think it would be interesting to have an HTML/CSS-like language in the future, and that would solve all the issues above (although maybe introducing others).

**Comment by llamahunter** [comment]
When do you plan to a) merge your WIP changes into the master, and b) push a new release?

**Comment by Meiguro** [comment]
It's merged into master now, sorry for the long wait. Pebble.js development is actually not officially supported, only its integration with CloudPebble is supported.

I was a little weary of pushing that many changes to master (it completely changes how action bars and status bars work to fix the bugginess on 3.0), but that's actually the best way to get it tested, so I'll be less hesitant in the future.

For all the changes to be released on CloudPebble, I will need to create a PR with updated documentation to be merged once the new version is live on CloudPebble. This should give enough time for people to test master.

To use color in the status bar, status is now a nested property similar to action:
```javascript
var card = new UI.Card({
  status: {
    separator: 'dotted', // 'dotted' or 'none'
    color: 'red', // separator and text color
    backgroundColor: 'white',
  },
});
```

I went with `color` instead of `textColor` since it specifies both the separator and text color, and theoretically the icon and pagination if that ever gets implemented/added to the base SDK.

**Comment by llamahunter** [comment]
Great.. thx.  Will fetch and take a look at it in the next few days.  This pull request is moot, right?

**Comment by Meiguro** [comment]
Yes, unless you have concerns with the API. I usually let the creator of a ticket/PR close the issue to know that it really is closed. Once again I'm really sorry about the whole issue of multiple independent implementations, it happens a lot with this kind of project. To prevent this from happening again, you can reach me on the pebbledev slack.

**Pull request closed without merging**
