### PR TITLE
Color support on Menus

### PR DESCRIPTION
**Pull request by fletchto99**
Ability to change the background color, text color, highlight background color, highlight text color

### CODE REVIEW

**Comment by Meiguro** [comment]
Nice work, thanks!

There's no pebble.js style guide yet (I should probably make one), but it is modified Google C++ style. 2-space for both C and JS, and the long line marker is 120.

If the platform differences become wildly unmanageable, I'll eventually modify the wscript to choose different .c files to compile in, with the headers possibly still being shared.

About the menu cache size, pebble.js used to not clear resources upon changing windows. Since it does now, there is plenty of space of menu items in menus. Thanks for bumping it.

**Comment by fletchto99** [comment]
I've found a bug with my implementation of colors (and possibly the previous implementation too). Since on Aplite there is no way to set the normal and highlighted colors on the menu, the only way to change way color is to set the window background color. This works fine on basalt platform when the normal background color and the the row color match, however on Aplite if you change the bwckground color to black, it results in a weird effect which sort of looks like the tearing bug. At first I though my pebble died! 

Perhaps it would be better to not set the window background color at all on Aplite? Let me know what you think and I'll get it fixed up tonight.

Also I've noticed that menu items with icons don't work properly if the icon color is the same as either the background color or the highlighted background color. I don't really see a way to prevent this other than common sense by the developer, however perhaps you might have a suggestion? Maybe invert the color of the icon if it's primary color is the same as the menus color?

Lastly... I attempted to implement a "Loading..." Text for menu items as they loaded, and while it kind of worked, the loading text would disappear really quickly and go blank for a second until the actual menu item appeared. I attempted to do this by adding a menu_draw_cell_basic in the draw row callback right before the actual item is requested. Perhaps you might know why this occurs? I tried a bunch of different things by it always resulted in the loading appearing and disappearing really quickly.

**Comment by fletchto99** [comment]
I've found a bug with my implementation of colors (and possibly the previous implementation too). Since on Aplite there is no way to set the normal and highlighted colors on the menu, the only way to change way color is to set the window background color. This works fine on basalt platform when the normal background color and the the row color match, however on Aplite if you change the bwckground color to black, it results in a weird effect which sort of looks like the tearing bug. At first I though my pebble died! 

Perhaps it would be better to not set the window background color at all on Aplite? Let me know what you think and I'll get it fixed up tonight.

Also I've noticed that menu items with icons don't work properly if the icon color is the same as either the background color or the highlighted background color. I don't really see a way to prevent this other than common sense by the developer, however perhaps you might have a suggestion? Maybe invert the color of the icon if it's primary color is the same as the menus color?

Lastly... I attempted to implement a "Loading..." Text for menu items as they loaded, and while it kind of worked, the loading text would disappear really quickly and go blank for a second until the actual menu item appeared. I attempted to do this by adding a menu_draw_cell_basic in the draw row callback right before the actual item is requested. Perhaps you might know why this occurs? I tried a bunch of different things by it always resulted in the loading appearing and disappearing really quickly.

**Comment by fletchto99** [comment]
Oh and one other question about the dynamic loading of menu items. It appears that the menu currently loads n items, and then once you reach the nth+1 item it loads some more. Would it be possible to make this load after n/2 items? So that there will always be a large padding of loaded menu items on each side of the selected one? I.E. There will be n/2 items loaded, selected one, (n/2)-1 items loaded? Where the end points would have special cases keeping all n items in the direction of the menu loaded?

Sorry if this wasn't very clear, I did my best to explain it. If you've got any questions let me know. I tried to implement this on the weekend but I couldn't seem to figure out the loading ahead part, it would always just shift the loaded menu item right to the selected index.

**Comment by fletchto99** [comment]
Here's the issue if you set the background color to 'red' and install it on aplite. I'll look into this, perhaps I suggest if it's aplite, then force the background to be either black or white

pebble-screenshot_2015-06-08_20-17-49

**Pull request merged**
