### PR TITLE
[WIP] Card for round displays

### PR DESCRIPTION
**Pull request by Meiguro**
This is a WIP of updating the Card window for round displays. I originally intended to update the styles as well, but it's a better idea to address that in a separate PR. I'm going to leave this up for a bit, and eventually merge it if there are no issues.

As for the code itself, simply_ui likely needs factoring out of functionality, but that should be for a later time.

### CODE REVIEW

**Comment by youtux** [comment]
Nice work! I found a couple of problems. Take the following snippet:
```javascript
var card = new UI.Card({
    title: 'A Card',
    subtitle: 'Is a Window',
    body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    scrollable: true,
    fullscreen: false
  });
  card.show();
```
1. On basalt, the subtitle is not correctly left-aligned
2. On chalk, the action bar is missing.
3. I don't know if this problem existed before this PR, but if you set the `scrollable` property after creating the `Card` object and then show it, it will not be scrollable.

screen shot 2015-10-15 at 22 10 57

**Comment by youtux** [comment]
Another problem: take the following snippet.
```javascript
var card = new UI.Card({
    title: 'Title t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t t',
    subtitle: 'Subtitle s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s',
    body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    scrollable: true,
    fullscreen: false
  });
card.show();
```

1. On basalt, the subtitle invades the body, as you can see from the screenshot:
screen shot 2015-10-15 at 22 21 07

2. On chalk, the title and the subtitle are completely messed up, while the body is correctly positioned. Also note from the first two screenshots that the text on the bottom is cut from the screen.


screen shot 2015-10-15 at 22 23 14
screen shot 2015-10-15 at 22 23 40
screen shot 2015-10-15 at 22 23 50
screen shot 2015-10-15 at 22 23 56

**Comment by Meiguro** [comment]
Thanks for testing!

There was a typo with in the PR affecting the subtitle. I've also disabled paging on basalt since it's not necessary until paging is manually supported. The subtitle overlap was a similar typo that I didn't catch until now, though I forgot to include the fix.

I will have to check out the `scrollable` issue in a different PR. Similarly, I'll be handling the status bar in a separate PR. I think I will get rid of compatibility logic and make it work like the native 3.0 apps.

Let me know how these particular fixes go.

**Comment by Meiguro** [comment]
Superseded by #136

**Pull request closed without merging**
