### PR TITLE
Light: new module

### PR DESCRIPTION
**Pull request by youtux**
This allows the control of the Pebble's backlight.

Simple app to test it:
```js
var UI = require('ui');
var Light = require('ui/light');

var main = new UI.Card({
  title: 'Light test',
  body: 'UP -> Light.on()\nSELECT -> Light.auto()\nDOWN -> Light.trigger()'
});

main.show();

main.on('click', 'up', function(e) {
  Light.on();
});

main.on('click', 'select', function(e) {
  Light.auto();
});

main.on('click', 'down', function(e) {
  Light.trigger();
})
```

### CODE REVIEW

**Comment by sarfata** [comment]
Really cool! Thanks a lot! 

Looks good to me but I will let @Meiguro review and confirm he is ok with it!

**Comment by Meiguro** [comment]
Nice work, it looks good! I just merged in it. Now you've seen the huge mess that is simply-pebble.js. I want to split that up some time.

**Comment by youtux** [comment]
Yep 😄 Now I'm considering to implement the "Wake Up" functionality.

**Comment by Meiguro** [comment]
Haha, I feel extremely bad about how much I've delayed that feature #7. I want to try to have the feature ready for a hackathon next week however, so I've finally been making progress in that area. simply_msg.c was getting huge so I decided to move the differing sections of simply_msg.c into their respective module files in order to make writing new C-dependent features more simple. It reduced code size by a few bytes as a bonus.

With that, I was able to use the wakeup API, but I think it needs some sugar similar to the settings module to feel at home with the pebble.js API's. If you've made some work I can merge with yours before I've finalized anything! I've still not a solution in place for how to calculate a timestamp for a certain time on a particular weekday for example. I may see if there is an MIT/BSD micro library, or write a small utility function.

**Comment by youtux** [comment]
I've just written a little function `Wakeup.schedule(timestamp, notify_missed)` that does what you expect, but nothing more :).

In the matter of the timestamp, I used the `moment.js` library that is already present under `vendor`:
```js
Wakeup.schedule = function(timestamp, notify_missed) {
  time_f = moment(timestamp * 1000);
  // HACK: because of no timezone support on the Pebble, we need to remove
  // the timezone from the timestamp
  var no_tz_time = moment(time_f.format('YYYY-MM-DDTHH:mm:ss') + "+00:00").unix();
  simply.impl.scheduleWakeup(no_tz_time, notify_missed);
};
```
The problem is that as soon as the Pebble OS will support the timezone, this will break badly.

**Comment by Meiguro** [comment]
Ah, for some reason I had thought I removed moment! I might make use of that for the weekday calculations.

We have nearly the same API then! I've decided to add a callback in case of scheduling errors, and will pack the event with information on what kind of failure. It is actually similar to the Settings module.

Yes, the timezone stuff is definitely nasty. There's also issues with app messages coming in before the app message listener is ready, making a wakeup event possibly missed. To work around these issues, I added Ready and LaunchReason. The watch sends the LaunchReason after receiving Ready which also contains the watch's current timestamp. I calculate a timeOffset within 30 minute resolution and use that to offset subsequent timestamps. timeOffset should be 0 when timezone support is added. The only issue is that timeOffset is initialized with the current timezoneOffset, so there is a small window of an incorrect timeOffset being used after such a new firmware.

Thinking about it again, I should test if no app messages are ever missed if app message is registered outside of the PebbleKit ready event.

**Comment by sarfata** [comment]
On Pebble you can detect [whether the timezone is set](http://developer.getpebble.com/docs/c/group___wall_time.html#ga95c658aa0d511e4b4ca549724e02ce72).

**Comment by youtux** [comment]
Right, we could ask the pebble if the timezone is set, otherwise use the "hack".

**Pull request merged**
