### PR TITLE
Update README for new package format

### PR DESCRIPTION
**Pull request by cjwilliams**
Feel free to point out any appinfo.json's, incorrect requires or other inaccuracies that I missed!

### CODE REVIEW

**Comment by Meiguro** [comment]
:+1: Thanks for updating the docs!

**Comment by matopeto** [comment]
Hi, very nice work with pebblejs as npm package.

But when i try simple code from docs it doesnt work:

```
Pebble.addEventListener("ready",
    function(e) {
var UI = require('pebblejs/ui');
var card = new UI.Card({
  title: 'Hello World',
  body: 'This is your first Pebble app!',
  scrollable: true
});
card.show();
        console.log("Hello world! - Sent from your javascript application.");
    }
);
```

Shows error:
```
matej@MATEJ-WORK-PC:~/pebblejspackagesample$ DISPLAY=:0 pebble install --emulator basalt --logs
Installing app...
App install succeeded.
[13:34:42] pkjs> TypeError: Cannot read property 'card' of undefined
    at Card._prop (pebble-js-app.js:1658:17)
    at Window._show (pebble-js-app.js:412:9)
    at WindowStack._show (pebble-js-app.js:1290:9)
    at WindowStack.push (pebble-js-app.js:1313:9)
    at Window.show (pebble-js-app.js:420:16)
    at Pebble.<anonymous> (pebble-js-app.js:89:7)
```

EDIT: Error is on this line: https://github.com/pebble/pebblejs/blob/0a5871ca591dd6df71974b7c0a076728fca95414/src/js/ui/card.js#L61

**Comment by Meiguro** [comment]
Hey @matopeto, thanks for trying it out!

It's a little hard to see since the tutorial has the source in pieces but you should have `require('pebblejs')` before everything for it to initialize. `card` is undefined since pebble.js is not fully loaded yet. Also, amazingly, you don't need to wrap your code in a ready handler.

So the top of your file should look like this
```js
require('pebblejs');
var UI = require('pebblejs/ui');
```

I'm probably going to change it to implicitly require since this seems like it could cause trouble.

**Comment by matopeto** [comment]
Thanks! I see it now. Implicit require will be better for those who converting "old" programs to new format.

**Comment by ToemD** [comment]
I don't if it here the correct place, but I cannot get compiled my project in cloudpebble.net with pebble.js npm and clay version 0.17 (for pebble.js)
```
WARNING in ./src/pkjs/clay.js
Critical dependencies:
2:412-419 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./src/pkjs/clay.js 2:412-419

ERROR in /app/sdk3/pebble/common/include/_message_key_wrapper.js
Module not found: Error: Cannot resolve module 'message_keys' in /app/sdk3/pebble/common/include
 @ /app/sdk3/pebble/common/include/_message_key_wrapper.js 3:36-59
```

Problem solved with one dummy message key.

**Comment by ToemD** [comment]
Now I get this runtime error:
```
TypeError: null is not an object (evaluating 'Pebble.getActiveWatchInfo().platform') at line 3151 in pebble-js-app.js
```

To workaround the runtime error I've used the Pebble.addEventListener('ready', function() { over all code in index.js

**Pull request merged**
